TelegramConfig    :
  BotName         : 'Quang_bot'
  BotToken        : '5379690042:AAHsmvcazskbA3zmC6IyINMp8k0rezViCGk'
  IdBotChat       : 2105095097

MqttConfig        : 
  Broker          : 'localhost:1883'
  TeleSrcTopic    : 'Telegram/Quang_bot/Rx'
  TeleDstTopic    : 'Telegram/Quang_bot/Tx'  