
MqttConfig        : 
  Broker          : 'localhost:1883'

  SerialSrcTopic  : 'Serial/COM4/Rx'
  SerialDstTopic  : 'Serial/COM4/Tx'

  TeleSrcTopic    : 'Telegram/Quang_bot/Rx'
  TeleDstTopic    : 'Telegram/Quang_bot/Tx'    

CmdConfig:

  ControlLedVN:
    - TokenCode: 
      - 'Bật đèn 1'
      - 'Bat den 1'
      - 'bật đèn 1'
      - 'bat den 1'
      Cmd              : 'ONLED: 1'
      ResponseMap:
         '1'           : 'Đèn 1 đã bật'

    - TokenCode: 
      - 'Tắt đèn 1'
      - 'Tat den 1'
      - 'tắt đèn 1'
      - 'tat den 1'
      Cmd              : 'OFFLED: 1'
      ResponseMap:
         '0'           : 'Đèn 1 đã tắt'

    - TokenCode: 
      - 'Bật đèn 2'
      - 'Bat den 2'
      - 'bật đèn 2'
      - 'bat den 2'      
      Cmd              : 'ONLED: 2'
      ResponseMap:
         '1'           : 'Đèn 2 đã bật'

    - TokenCode: 
      - 'Tắt đèn 2'
      - 'Tat den 2'
      - 'tắt đèn 2'
      - 'tat den 2'
      Cmd              : 'OFFLED: 2'
      ResponseMap:
         '0'           : 'Đèn 2 đã tắt'

  ControlLedEN:
    - TokenCode:        
      - 'Led 1 on'
      - 'LED 1 ON'
      Cmd              : 'ONLED: 1'
      ResponseMap:
         '1a'           : 'Led 1 was on'

    - TokenCode:        
      - 'Led 1 off'
      - 'LED 1 OFF'
      Cmd              : 'OFFLED: 1'
      ResponseMap:
         '0'           : 'Led 1 was off'        

    - TokenCode:        
      - 'Led 2 on'
      - 'LED 2 ON'
      Cmd              : 'ONLED: 2'
      ResponseMap:
         '1'           : 'Led 2 was on'

    - TokenCode: 
      - 'Led 2 off'
      - 'LED 2 OFF'
      Cmd              : 'OFFLED: 2'
      ResponseMap:
         '0'           : 'Led 2 was off'           

  DefaultRespMsg       : 'Wrong command. Please try again!'
  ErrorCmdVN           : 'Lệnh chưa được cấu hình'        
  ErrorCmdEN           : 'Command has not been initialized'    
  TimeoutRespMsgVN     : 'Quá thời gian, không nhận được phản hồi từ thiết bị'
  TimeoutRespMsgEN     : 'Time out, no response from device'
  TickTimeout          : 3
