
MqttConfig        : 
  Broker          : 'localhost:1883'

  SerialSrcTopic  : 'Serial/COM4/Rx'
  SerialDstTopic  : 'Serial/COM4/Tx'

  TeleSrcTopic    : 'Telegram/Quang_bot/Rx'
  TeleDstTopic    : 'Telegram/Quang_bot/Tx'    

CmdConfig:

  ControlLedVN:
    - ChatCmd: 
      - 'Bật đèn 1'
      - 'Bat den 1'
      - 'bật đèn 1'
      - 'bat den 1'
      DeviceCmd        : 'ONLED: 1'
      ChatResponseMap:
         '1a'           : 'Đèn 1 đã bật'

    - ChatCmd: 
      - 'Tắt đèn 1'
      - 'Tat den 1'
      - 'tắt đèn 1'
      - 'tat den 1'
      DeviceCmd        : 'OFFLED: 1'
      ChatResponseMap:
         '0'           : 'Đèn 1 đã tắt'

    - ChatCmd: 
      - 'Bật đèn 2'
      - 'Bat den 2'
      - 'bật đèn 2'
      - 'bat den 2'      
      DeviceCmd        : 'ONLED: 2'
      ChatResponseMap:
         '1'           : 'Đèn 2 đã bật'

    - ChatCmd: 
      - 'Tắt đèn 2'
      - 'Tat den 2'
      - 'tắt đèn 2'
      - 'tat den 2'
      DeviceCmd        : 'OFFLED: 2'
      ChatResponseMap:
         '0'           : 'Đèn 2 đã tắt'

  ControlLedEN:
    - ChatCmd:        
      - 'Led 1 on'
      - 'LED 1 ON'
      DeviceCmd        : 'ONLED: 1'
      ChatResponseMap:
         '1a'          : 'Led 1 was on'

    - ChatCmd:        
      - 'Led 1 off'
      - 'LED 1 OFF'
      DeviceCmd        : 'OFFLED: 1'
      ChatResponseMap:
         '0'           : 'Led 1 was off'        

    - ChatCmd:        
      - 'Led 2 on'
      - 'LED 2 ON'
      DeviceCmd        : 'ONLED: 2'
      ChatResponseMap:
         '1'           : 'Led 2 was on'

    - ChatCmd: 
      - 'Led 2 off'
      - 'LED 2 OFF'
      DeviceCmd        : 'OFFLED: 2'
      ChatResponseMap:
         '0'           : 'Led 2 was off' 
  # ChatResponseFailedVN:
  #   'TIMEOUT'          :  'Quá thời gian, không nhận được phản hồi từ thiết bị'             
  #   'UNKNOWNCMD'

  # ChatResponseFailedEN:
  #   'TIMEOUT'          :  'Time out, no response from device'  
  #   'UNKNOWNCMD'

  DefaultRespMsg       : 'Wrong command. Please try again!'
  ErrorCmdVN           : 'Yêu cầu không rõ. Bạn có thể yêu cầu:'        
  ErrorCmdEN           : 'Unknown request. You can ask:'    
  TimeoutRespMsgVN     : 'Quá thời gian, không nhận được phản hồi từ thiết bị'
  TimeoutRespMsgEN     : 'Time out, no response from device'
  TickTimeout          : 3
