MqttConfig               : 
  # Broker               : 'orangepione:1883'
  Broker                 : 'localhost:1883'
  User                   : 'nmtam'
  Password               : '221220'
  LedDeviceSrcTopic      : 'xuong/+/led/status'
  LedDeviceDstTopic      : 'xuong/telegram/led/cmd'
  TeleSrcTopic           : 'Telegram/+/Rx'
  TeleDstTopic           : 'Telegram/GroupID/Tx'
  SensorDeviceSrcTopic   : 'xuong/+/sensor/status'
  SensorDeviceDstTopic   : 'xuong/espID/sensor/cmd'

CmdConfig:

  ControlDeviceVN:
    - ChatCmd           : 'Bật đèn phòng khách'
      DeviceCmd         : 'ON1'
      ChatResponseMap   :
         'ON1'          : 'Đèn phòng khách đã bật'

    - ChatCmd           :  'Tắt đèn phòng khách'
      DeviceCmd         : 'OFF1'
      ChatResponseMap   :
         'OFF1'         : 'Đèn phòng khách đã tắt'

    - ChatCmd           : 'Bật đèn phòng bếp'   
      DeviceCmd         : 'ON2'
      ChatResponseMap   :
         'ON2'          : 'Đèn phòng bếp đã bật'

    - ChatCmd           : 'Tắt đèn phòng bếp'
      DeviceCmd         : 'OFF2'
      ChatResponseMap   :
         'OFF2'         : 'Đèn phòng bếp đã tắt'

    - ChatCmd           : 'Nhiệt độ phòng bếp'
      DeviceCmd         : 'TEMP1'
      ChatResponseMap   :
         'Sensor'       : 'Phòng bếp: '

  ControlDeviceEN:
    - ChatCmd           : 'Light living room on'
      DeviceCmd         : 'ON1'
      ChatResponseMap   :
         'ON1'          : 'Light living room was on'

    - ChatCmd           : 'Light living room off'
      DeviceCmd         : 'OFF1'
      ChatResponseMap   :
         'OFF1'         : 'Light living room was off'        

    - ChatCmd           : 'Light kitchen on'
      DeviceCmd         : 'ON2'
      ChatResponseMap   :
         'ON2'          : 'Light kitchen was on'

    - ChatCmd           : 'Light kitchen off'
      DeviceCmd         : 'OFF2'
      ChatResponseMap   :
         'OFF2'         : 'Light kitchen was off' 

    - ChatCmd           : 'Kitchen temperature'
      DeviceCmd         : 'TEMP1'
      ChatResponseMap   :
         'Sensor'       : 'Kitchen: ' 

  DefaultRespMsg:
    'ErrorCmd'         : 'Command not configured. Please try again!'
    'TimeoutVN'        : 'Quá thời gian, không nhận được phản hồi từ thiết bị'
    'TimeoutEN'        : 'Time out, no response from device'
    'ResponseHelpVN'   : 'Yêu cầu không rõ, bạn có thể thử'
    'ResponseHelpEN'   : 'Request unknown, you can request'   
    'SuggestVN'        : 'Có phải bạn muốn:'
    'SuggestEN'        : 'Do you want:'

  TickTimeout: 2 
  StringRateThreshold: 50.0
  GroupIDLedDevice: '2105095097'
  BotPassword: '68686868'